#!/usr/bin/env python

import sys
import validators

for line in sys.stdin:
    line = line.rstrip('\n').rstrip('\r')
    original = line
    
    if "://" in line:
        line = line.split("://")[1] # discard protocol

    if "/" in line:
        line = line.split("/")[0] # discard parameters

    if ":" in line:
        line = line.split(":")[0] # discard port

    if line.endswith("."):
        line = line[:-1] # discard ending .

    if line.startswith("*"):
        line = line[1:] # discard starting *

    if line.startswith("."):
        line = line[1:] # discard starting .

    if not validators.domain(line):
        print("[bad] ", original)