#!/usr/bin/env python

import sys
import validators

def isdom(line):
    line = line.rstrip('\n').rstrip('\r')
    if "://" in line:
        line = line.split("://")[1] # discard protocol

    if "/" in line:
        line = line.split("/")[0] # discard parameters

    if ":" in line:
        line = line.split(":")[0] # discard port

    if line.endswith("."):
        line = line[:-1] # discard ending .

    if line.endswith(","):
        line = line[:-1] # discard ending ,

    if line.startswith("*"):
        line = line[1:] # discard starting *

    if line.startswith("."):
        line = line[1:] # discard starting .

    if validators.domain(line):
        print(line)

for line in sys.stdin:
    for piece in line.split(' '):
        for piece2 in piece.split(','):
            isdom(piece2)