#!/usr/bin/env python

import sys

if not len(sys.argv) == 3:
    print("usage: isnew comp1 comp2 [shows the difference of two files]")
    quit(-1)

set1 = set()
set2 = set()
with open(sys.argv[1], 'r') as file:
    for line in file.read().split('\n'):
        dom = line.rstrip('\n').rstrip('\r')
        set1.add(dom)

with open(sys.argv[2], 'r') as file:
    for line in file.read().split('\n'):
        dom = line.rstrip('\n').rstrip('\r')
        set2.add(dom)
        
diff = set1.symmetric_difference(set2)

for dom in diff:
    print(dom)